import type { Metadata } from "next";
import {gtEestiProDisplayMedium, gtEestiProDisplayRegular} from "@/app/fonts/fonts";
import "./globals.css";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
        className={`${gtEestiProDisplayMedium.variable} ${gtEestiProDisplayRegular.variable} antialiased`}
    >
    <Script src="https://telegram.org/js/telegram-web-app.js" strategy={"beforeInteractive"}/>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"/>
    {children}
    </body>
    </html>
  );
}
