import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Script from "next/script";

const gtEestiProDisplayRegular = localFont({
    src: "./fonts/gteestiprodisplay_regular.otf",
    variable: "--font-gteestiprodisplay_medium",
    weight: "400",
});

const gtEestiProDisplayMedium = localFont({
  src: "./fonts/gteestiprodisplay_medium.otf",
  variable: "--font-gteestiprodisplay_medium",
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
        className={`${gtEestiProDisplayMedium.variable} ${gtEestiProDisplayRegular.variable} antialiased`}
    >
    <Script src="https://telegram.org/js/telegram-web-app.js" strategy={"beforeInteractive"} />
    {children}
    </body>
    </html>
  );
}
